/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 * La classe AjoutDialog représent une des tois composant de l'architecture MVC
 * la view, l'ajout modale.
 *
 * @author r.pina
 */
public class AjoutDialog extends javax.swing.JDialog {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    /**
     * Méthode d'insertion de PropertyChangeListener au lisetener
     *
     * @param l
     */
    public void addPropertyChangeListener(PropertyChangeListener l) {
        this.listeners.addPropertyChangeListener(l);
    }

    /**
     * Méthode qui récupère le nom d'un utilisateur à ajouté
     *
     * @return String
     */
    public String getUserAddNom() {
        return this.ajoutUserNomTxtField.getText();
    }

    /**
     * Méthode qui récupère le prénom d'un utilisateur à ajouté
     *
     * @return String
     */
    public String getUserAddPrenom() {
        return this.ajoutUserPrenomTxtField.getText();
    }

    /**
     * Méthode qui récupère l'adresse d'un utilisateur à ajouté
     *
     * @return String
     */
    public String getUserAddAdresse() {
        return this.ajoutUserAdresseTxtField.getText();
    }

    /**
     * Méthode qui récupère le pseudo d'un utilisateur à ajouté
     *
     * @return String
     */
    public String getUserAddPseudo() {
        return this.ajoutUserPseudoTxtField.getText();
    }

    /**
     * Méthode qui récupère le mot de passe d'un utilisateur à ajouté
     *
     * @return String
     */
    public String getUserAddMdp() {
        return this.ajoutUserMdpTxtField.getText();
    }

    /**
     * Méthode qui va affecter un nom d'un utilisateur
     *
     * @param userNom
     */
    public void setUserAddNom(String userNom) {
        this.ajoutUserNomTxtField.setText(userNom);
    }

    /**
     * Méthode qui va affecter un prénom d'un utilisateur
     *
     * @param userPrenom
     */
    public void setUserAddPrenom(String userPrenom) {
        this.ajoutUserPrenomTxtField.setText(userPrenom);
    }

    /**
     * Méthode qui va affecter un adresse d'un utilisateur
     *
     * @param userAdresse
     */
    public void setUserAddAdresse(String userAdresse) {
        this.ajoutUserAdresseTxtField.setText(userAdresse);
    }

    /**
     * Méthode qui va affecter un pseudo d'un utilisateur
     *
     * @param userPseudo
     */
    public void setUserAddPseudo(String userPseudo) {
        this.ajoutUserPseudoTxtField.setText(userPseudo);
    }

    /**
     * Méthode qui va affecter un mot de passe d'un utilisateur
     *
     * @param userMdp
     */
    public void setUserAddMdp(String userMdp) {
        this.ajoutUserMdpTxtField.setText(userMdp);
    }

    /**
     * Creates new form AjoutDialog
     */
    public AjoutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ajoutUserNomLabel = new javax.swing.JLabel();
        ajoutUserNomTxtField = new javax.swing.JTextField();
        ajoutUserPrenomLabel = new javax.swing.JLabel();
        ajoutUserAdresseLabel = new javax.swing.JLabel();
        ajoutUserMdpLabel = new javax.swing.JLabel();
        ajoutUserMdpTxtField = new javax.swing.JTextField();
        ajoutUserAdresseTxtField = new javax.swing.JTextField();
        ajoutUserPrenomTxtField = new javax.swing.JTextField();
        ajoutUserBtnValid = new javax.swing.JButton();
        ajoutUserBtnAnnule = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ajoutUserPseudoTxtField = new javax.swing.JTextField();
        ajoutUserPseudoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ajoutUserNomLabel.setDisplayedMnemonic('a');
        ajoutUserNomLabel.setText("Nom");

        ajoutUserPrenomLabel.setText("Prénom");

        ajoutUserAdresseLabel.setText("Adresse");

        ajoutUserMdpLabel.setText("Mot de passe");

        ajoutUserBtnValid.setText("Ajouter");
        ajoutUserBtnValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutUserBtnValidActionPerformed(evt);
            }
        });

        ajoutUserBtnAnnule.setText("Annulé");
        ajoutUserBtnAnnule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutUserBtnAnnuleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Nouvel utilisateur");

        ajoutUserPseudoLabel.setText("Pseudo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ajoutUserAdresseLabel)
                            .addComponent(ajoutUserMdpLabel)
                            .addComponent(ajoutUserPrenomLabel)
                            .addComponent(ajoutUserNomLabel)
                            .addComponent(ajoutUserPseudoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ajoutUserMdpTxtField)
                                .addComponent(ajoutUserAdresseTxtField)
                                .addComponent(ajoutUserPrenomTxtField)
                                .addComponent(ajoutUserNomTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ajoutUserBtnValid)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ajoutUserBtnAnnule))
                                .addComponent(ajoutUserPseudoTxtField)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutUserNomTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajoutUserNomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutUserPrenomTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajoutUserPrenomLabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutUserAdresseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajoutUserAdresseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutUserPseudoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajoutUserPseudoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutUserMdpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajoutUserMdpLabel))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutUserBtnValid)
                    .addComponent(ajoutUserBtnAnnule))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Méthode qui écoute lors d'un action sur le bouton "Ajouter" de la modale
     * ajout.
     */
    private void ajoutUserBtnValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutUserBtnValidActionPerformed
        // TODO add your handling code here:
        this.listeners.firePropertyChange("validNouvelUser", null, null);
    }//GEN-LAST:event_ajoutUserBtnValidActionPerformed

    /**
     * Méthode qui écoute lors d'un action sur le bouton "Annuler" de la modale
     * ajout.
     */
    private void ajoutUserBtnAnnuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutUserBtnAnnuleActionPerformed
        // TODO add your handling code here:
        this.listeners.firePropertyChange("closeAddDialog", null, null);
    }//GEN-LAST:event_ajoutUserBtnAnnuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutDialog dialog = new AjoutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajoutUserAdresseLabel;
    private javax.swing.JTextField ajoutUserAdresseTxtField;
    private javax.swing.JButton ajoutUserBtnAnnule;
    private javax.swing.JButton ajoutUserBtnValid;
    private javax.swing.JLabel ajoutUserMdpLabel;
    private javax.swing.JTextField ajoutUserMdpTxtField;
    private javax.swing.JLabel ajoutUserNomLabel;
    private javax.swing.JTextField ajoutUserNomTxtField;
    private javax.swing.JLabel ajoutUserPrenomLabel;
    private javax.swing.JTextField ajoutUserPrenomTxtField;
    private javax.swing.JLabel ajoutUserPseudoLabel;
    private javax.swing.JTextField ajoutUserPseudoTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
