package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 * La classe AjoutDialog représent une des tois composant de l'architecture MVC
 * la view, la modification modale.
 *
 * @author r.pina
 */
public class ModifDialog extends javax.swing.JDialog {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);
    private int userModifId;

    /**
     * Creates new form ModifDialog
     */
    public ModifDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Méthode d'insertion de PropertyChangeListener au lisetener
     *
     * @param l
     */
    public void addPropertyChangeListener(PropertyChangeListener l) {
        this.listeners.addPropertyChangeListener(l);
    }

    /**
     * Méthode qui récupère l'id d'un utilisateur modifié
     *
     * @return Integer
     */
    public int getUserModifId() {
        return this.userModifId;
    }

    /**
     * Méthode qui récupère le nom d'un utilisateur modifié.
     *
     * @return String
     */
    public String getUserModifNom() {
        return this.modifUserNomTxtField.getText();
    }

    /**
     * Méthode qui récupère le prénom d'un utilisateur modifié.
     *
     * @return String
     */
    public String getUserModifPrenom() {
        return this.modifUserPrenomTxtField.getText();
    }

    /**
     * Méthode qui récupère l'adresse d'un utilisateur modifié.
     *
     * @return String
     */
    public String getUserModifAdresse() {
        return this.modifUserAdresseTxtField.getText();
    }

    /**
     * Méthode qui récupère le pseudo d'un utilisateur modifié.
     *
     * @return String
     */
    public String getUserModifPseudo() {
        return this.modifUserPseudoTxtField.getText();
    }

    /**
     * Méthode qui récupère le mot de passe d'un utilisateur modifié.
     *
     * @return String
     */
    public String getUserModifMdp() {
        return this.modifUserMdpTxtField.getText();
    }

    /**
     * Méthode qui va affecter l'id d'un utilisateur sur le champ de texte
     *
     * @param userId
     */
    public void setUserModifId(int userId) {
        this.userModifId = userId;
    }

    /**
     * Méthode qui va affecter le nom d'un utilisateur sur le champ de texte
     *
     * @param userNom
     */
    public void setUserModifNom(String userNom) {
        this.modifUserNomTxtField.setText(userNom);
    }

    /**
     * Méthode qui va affecter le prénom d'un utilisateur sur le champ de texte
     *
     * @param userPrenom
     */
    public void setUserModifPrenom(String userPrenom) {
        this.modifUserPrenomTxtField.setText(userPrenom);
    }

    /**
     * Méthode qui va affecter l'adresse d'un utilisateur sur le champ de texte
     *
     * @param userAdresse
     */
    public void setUserModifAdresse(String userAdresse) {
        this.modifUserAdresseTxtField.setText(userAdresse);
    }

    /**
     * Méthode qui va affecter le pseudo d'un utilisateur sur le champ de texte
     *
     * @param userPseudo
     */
    public void setUserModifPseudo(String userPseudo) {
        this.modifUserPseudoTxtField.setText(userPseudo);
    }

    /**
     * Méthode qui va affecter le mot de passe d'un utilisateur sur le champ de
     * texte
     *
     * @param userMdp
     */
    public void setUserModifMdp(String userMdp) {
        this.modifUserMdpTxtField.setText(userMdp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifUserPrenomTxtField = new javax.swing.JTextField();
        modifUserPrenomLabel = new javax.swing.JLabel();
        modifUserNomLabel = new javax.swing.JLabel();
        modifUserNomTxtField = new javax.swing.JTextField();
        modifUserMdpLabel = new javax.swing.JLabel();
        modifUserMdpTxtField = new javax.swing.JTextField();
        modifUserAdresseLabel = new javax.swing.JLabel();
        modifUserAdresseTxtField = new javax.swing.JTextField();
        modifUserBtnValid = new javax.swing.JButton();
        modifUserBtnAnnule = new javax.swing.JButton();
        modifUserTitreLabel = new javax.swing.JLabel();
        modifUserPseudoLabel = new javax.swing.JLabel();
        modifUserPseudoTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modifUserPrenomLabel.setText("Prénom");

        modifUserNomLabel.setText("Nom");

        modifUserMdpLabel.setText("Mot de passe");

        modifUserAdresseLabel.setText("Adresse");

        modifUserBtnValid.setText("Modifier");
        modifUserBtnValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifUserBtnValidActionPerformed(evt);
            }
        });

        modifUserBtnAnnule.setText("Annulé");
        modifUserBtnAnnule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifUserBtnAnnuleActionPerformed(evt);
            }
        });

        modifUserTitreLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        modifUserTitreLabel.setText("Modification de l'utilisateur");

        modifUserPseudoLabel.setText("Pseudo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(modifUserTitreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(modifUserPrenomLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(modifUserNomLabel)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifUserPrenomTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifUserNomTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(modifUserAdresseLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modifUserMdpLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifUserAdresseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(modifUserBtnValid)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modifUserBtnAnnule))
                                .addComponent(modifUserMdpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(modifUserPseudoLabel)
                        .addGap(4, 4, 4)
                        .addComponent(modifUserPseudoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(modifUserTitreLabel)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifUserNomLabel)
                    .addComponent(modifUserNomTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifUserPrenomLabel)
                    .addComponent(modifUserPrenomTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifUserAdresseLabel)
                    .addComponent(modifUserAdresseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifUserPseudoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifUserPseudoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifUserMdpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifUserMdpLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifUserBtnAnnule)
                    .addComponent(modifUserBtnValid))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Méthode qui écoute lors d'un action sur le bouton "Modifier" du modale
     * modifier.
     */
    private void modifUserBtnValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifUserBtnValidActionPerformed
        this.listeners.firePropertyChange("validModifUser", null, null);
    }//GEN-LAST:event_modifUserBtnValidActionPerformed

    /**
     * Méthode qui écoute lors d'un action sur le bouton "Annuler" du modale
     * modifier.
     */
    private void modifUserBtnAnnuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifUserBtnAnnuleActionPerformed
        // TODO add your handling code here:
        this.listeners.firePropertyChange("closeModifDialog", null, null);
    }//GEN-LAST:event_modifUserBtnAnnuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifDialog dialog = new ModifDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel modifUserAdresseLabel;
    private javax.swing.JTextField modifUserAdresseTxtField;
    private javax.swing.JButton modifUserBtnAnnule;
    private javax.swing.JButton modifUserBtnValid;
    private javax.swing.JLabel modifUserMdpLabel;
    private javax.swing.JTextField modifUserMdpTxtField;
    private javax.swing.JLabel modifUserNomLabel;
    private javax.swing.JTextField modifUserNomTxtField;
    private javax.swing.JLabel modifUserPrenomLabel;
    private javax.swing.JTextField modifUserPrenomTxtField;
    private javax.swing.JLabel modifUserPseudoLabel;
    private javax.swing.JTextField modifUserPseudoTxtField;
    private javax.swing.JLabel modifUserTitreLabel;
    // End of variables declaration//GEN-END:variables
}
